# Generated by Django 3.0.4 on 2020-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('main_image', models.ImageField(default='', upload_to='main/')),
                ('main_about', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
