# Generated by Django 3.0.4 on 2020-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200515_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='main_image',
            new_name='card_image',
        ),
        migrations.AddField(
            model_name='projects',
            name='proj_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='main_about',
            field=models.TextField(default='', max_length=40000000000000),
        ),
    ]
