# Generated by Django 3.0.4 on 2020-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200515_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='card_image',
            new_name='main_image',
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='projects/', verbose_name='Video'),
        ),
    ]
