# Generated by Django 3.0.4 on 2020-05-18 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects_is_muted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_muted',
            field=models.BooleanField(default=True, verbose_name='If video has sound uncheck this'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='main_about',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(150)]),
        ),
    ]
