# Generated by Django 3.0.4 on 2020-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200518_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='certi_name',
            field=models.CharField(max_length=500),
        ),
    ]
