# Generated by Django 3.0.4 on 2020-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_certifications_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='git_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
