# Generated by Django 3.0.4 on 2020-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200522_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_top',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
